[target.x86_64-unknown-linux-musl]
image = "joseluisq/rust-linux-darwin-builder:1.83.0"

[target.aarch64-unknown-linux-musl]
image = "joseluisq/rust-linux-darwin-builder:1.83.0"

[target.x86_64-apple-darwin]
image = "joseluisq/rust-linux-darwin-builder:1.83.0"

[target.aarch64-apple-darwin]
image = "joseluisq/rust-linux-darwin-builder:1.83.0"

[target.aarch64-apple-darwin.env]
CC = o64-clang
CXX = o64-clang++

