name: Build Template

on:
  workflow_call:
    inputs:
      runner:
        required: false
        type: string
        default: "ubuntu-22.04"
      distr:
        required: true
        type: string
      arch:
        required: true
        type: string
      artifact_list:
        required: false
        type: string
        default: "target/release/lib*.so"
      setup:
        required: false
        type: string
        default: ""

jobs:
  build:
    runs-on: ${{ inputs.runner }}
    defaults:
      run:
        shell: bash
    timeout-minutes: 30
    steps:
      - name: Setup
        if: ${{ inputs.setup }}
        run: |
          ${{ inputs.setup }}
        shell: bash

      - name: Check distribution type
        id: vars
        run: |
          declare -A image_map=(
            [bionic]="ubuntu:bionic"
            [focal]="ubuntu:focal"
            [jammy]="ubuntu:jammy"
            [buster]="debian:buster"
            [bullseye]="debian:bullseye"
            [bookworm]="debian:bookworm"
            [rhel7]="oraclelinux:7"
            [rhel8]="oraclelinux:8"
            [rhel8]="oraclelinux:9"
          )

          image=${image_map[${{ inputs.distr }}]}
          echo "image=${image}" >> $GITHUB_OUTPUT

          declare -A target_map=(
            [bionic]="unknown-linux-gnu"
            [focal]="unknown-linux-gnu"
            [jammy]="unknown-linux-gnu"
            [buster]="unknown-linux-gnu"
            [bullseye]="unknown-linux-gnu"
            [bookworm]="unknown-linux-gnu"
            [rhel7]="unknown-linux-gnu"
            [rhel8]="unknown-linux-gnu"
            [rhel9]="unknown-linux-gnu"
            [macos]="apple-darwin-gcc"
            [windows]="pc-windows-msvc"
          )

          if [[ -n "${target_map[${{ inputs.distr }}]}" ]]; then
            echo "target=${{ inputs.arch }}-${target_map[${{ inputs.distr }}]}" >> $GITHUB_OUTPUT
          else
            echo "Unsupported distribution type: ${{ inputs.distr }}"
            exit 1
          fi

      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ steps.vars.outputs.target }}
          override: true
      - name: Prepare build args
        id: params
        run: |
          args=(
            "--target" 
            "${{ steps.vars.outputs.target }}" 
            "--lib"
            "--release" 
            "--manifest-path" 
            "./embeddings/Cargo.toml"
          )
          echo "args=${args[@]}" >> $GITHUB_OUTPUT

          platform=debian
          if [[ "${{ inputs.distr }}" =~ rhel.* ]]; then
            platform=rhel
          elif [[ "${{ inputs.distr }}" =~ macos.* ]]; then
            platform=macos
          elif [[ "${{ inputs.distr }}" =~ windows.* ]]; then
            platform=windows
          fi

          cross_template="./embeddings/Cross.toml.${platform}"
          if [[ -f $cross_template ]]; then
            export CROSS_IMAGE="${{ steps.vars.outputs.image }}"
            envsubst < $cross_template > "./embeddings/Cross.toml"
          fi

      - name: Build
        uses: actions-rs/cargo@v1
        env:
          CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: ${{ inputs.arch == 'aarch64' && 'aarch64-linux-gnu-gcc' || ''}}
          CC_aarch64_unknown_linux_gnu: ${{ inputs.arch == 'aarch64' && 'aarch64-linux-gnu-gcc' || ''}}
          CXX_aarch64_unknown_linux_gnu: ${{ inputs.arch == 'aarch64' && 'aarch64-linux-gnu-g++' || ''}}
        with:
          use-cross: true
          command: build
          args: ${{ steps.params.outputs.args }}
      - run: | 
          mkdir build
          ls -lt ./embeddings/target/*/*/libmanticoresearch*.so
          mv ./embeddings/target/*/*/libmanticoresearch*.so ./build

      - name: Upload build artifacts
        if: success()
        uses: manticoresoftware/upload_artifact_with_retries@v2
        with:
          name: build_${{ inputs.distr }}_${{ inputs.CTEST_CONFIGURATION_TYPE }}_${{ inputs.arch }}
          path: ./build/*
