name: 📦 Pack and publish
run-name: 📦 Pack and publish ${{ github.sha }}

#on: workflow_call
on:
  workflow_run:
    workflows: [ 🔬 Test ]
    types: [ completed ]
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [opened, synchronize, reopened, labeled, unlabeled]
  push:
    branches:
      - columnar-*

# cancels the previous workflow run when a new one appears in the same branch (e.g. master or a PR's branch)
concurrency:
  group: pack_${{ github.ref }}
  cancel-in-progress: true

jobs:
  embedding_pack:
    uses: ./.github/workflows/embedding_build_template.yml
    strategy:
      fail-fast: false
      matrix:
        distr: [jammy, rhel9]
        arch: [x86_64, aarch64]
    name: ${{ matrix.distr }} ${{ matrix.arch }} embedding packing
    with:
      runner: ubuntu-22.04
      distr: ${{ matrix.distr }}
      arch: ${{ matrix.arch }}

