name: 📦 Pack and publish
run-name: 📦 Pack and publish ${{ github.sha }}

#on: workflow_call
on:
  workflow_run:
    workflows: [ 🔬 Test ]
    types: [ completed ]
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [opened, synchronize, reopened, labeled, unlabeled]
  push:
    branches:
      - columnar-*

# cancels the previous workflow run when a new one appears in the same branch (e.g. master or a PR's branch)
concurrency:
  group: pack_${{ github.ref }}
  cancel-in-progress: true

jobs:

  pack:
    name: OK to pack?
    runs-on: ubuntu-22.04
    if: |
      (github.event_name == 'pull_request' && (contains(github.event.pull_request.labels.*.name, 'pack') || contains(github.event.pull_request.labels.*.name, 'publish')))
      || (github.event_name == 'push')
      || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/master' && github.event.workflow_run.event != 'schedule')
    steps:
      - run: echo "All set to build packages"

  embedding_pack:
    uses: ./.github/workflows/embedding_build_template.yml
    needs: pack
    strategy:
      fail-fast: false
      matrix:
        distr: [bionic, focal, jammy, buster, bullseye, bookworm]
        arch: [x86_64, aarch64]
    name: ${{ matrix.distr }} ${{ matrix.arch }} embedding packing
    with:
      image: ubuntu-22.04
      distr: ${{ matrix.distr }}
      arch: ${{ matrix.arch }}

